services:
  - type: web
    name: backend-reliable
    env: docker
    buildCommand: |
      apt-get update && apt-get install -y unzip curl php-cli php-mbstring git && \
      curl -sS https://getcomposer.org/installer | php && \
      php composer.phar install
    startCommand: apache2-foreground
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
